services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: banvic
      POSTGRES_USER: data_engineer
      POSTGRES_PASSWORD: v3rysecur&pas5w0rd
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./banvic.sql:/docker-entrypoint-initdb.d/banvic.sql
    ports:
      - 55432:5432
  dw:
    image: postgres:16
    container_name: banvic_data_warehouse
    environment:
      POSTGRES_DB: seu_datawarehouse
      POSTGRES_USER: usuario_dw
      POSTGRES_PASSWORD: senha_dw
    ports:
      - 5433:5432
